# Generated by Django 5.0.4 on 2024-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, help_text='Введите ссылку на видео', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
