# Generated by Django 5.0.4 on 2024-05-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_subscriptioncourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioncourse',
            name='subscription_is_active',
        ),
    ]
